package hospital

open class Empleado(nroDni: Int,
                    nombre: String,
                    apellido:String,
                    fecNacimiento: String,
                    direccion: String,
                    ciudadOrig: String,
                    val codEmpleado: Int,
                    val nroHorasExtra: Int,
                    val fecIngreso: String,
                    val area: String,
                    val cargo:String) : Persona(nroDni, nombre, apellido, fecNacimiento, direccion, ciudadOrig)

open class Empleadoxplanilla(nroDni: Int,
                             nombre: String,
                             apellido:String,
                             fecNacimiento: String,
                             direccion: String,
                             ciudadOrig: String,
                             codEmpleado: Int,
                             nroHorasExtra: Int,
                             fecIngreso: String,
                             area: String,
                             cargo:String,
                             val salarioMensual: Double,
                             val porcentajeAdicional: Double) : Empleado(nroDni, nombre, apellido, fecNacimiento, direccion, ciudadOrig, codEmpleado, nroHorasExtra, fecIngreso, area, cargo)

class EmpleadoEventual(nroDni: Int,
                       nombre: String,
                       apellido:String,
                       fecNacimiento: String,
                       direccion: String,
                       ciudadOrig: String,
                       codEmpleado: Int,
                       nroHorasExtra: Int,
                       fecIngreso: String,
                       area: String,
                       cargo:String,
                       val honorariosxHora: Double,
                       val nroHorasTotales: Int,
                       val fechaFinContrato: String) : Empleado(nroDni, nombre, apellido, fecNacimiento, direccion, ciudadOrig, codEmpleado, nroHorasExtra, fecIngreso, area, cargo)

class Medico(nroDni: Int,
             nombre: String,
             apellido:String,
             fecNacimiento: String,
             direccion: String,
             ciudadOrig: String,
             codEmpleado: Int,
             nroHorasExtra: Int,
             fecIngreso: String,
             area: String,
             cargo:String,
             salarioMensual: Double,
             porcentajeAdicional: Double,
             val especialidad: String,
             val servicio: String,
             val nroConsultorio: Int) : Empleadoxplanilla(nroDni, nombre, apellido, fecNacimiento, direccion, ciudadOrig, codEmpleado, nroHorasExtra, fecIngreso, area, cargo, salarioMensual, porcentajeAdicional)